version: "3.8"
services:
  app:
    image: webdevops/php-nginx-dev:8.0
    volumes:
      - ./:/app
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
      - WEB_DOCUMENT_INDEX=index.php
      - REDIS_URL=redis://redis
    ports:
      - 8000:80
    depends_on:
      - database
      - redis
  database:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: main
      POSTGRES_PASSWORD: main
      POSTGRES_DB: main
    ports:
      - "5432:5432"
  redis:
    image: redis:5-alpine
    ports:
      - "6379:6379"

